//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetMake.Shared.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class General {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal General() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BudgetMake.Shared.Common.Resources.General", typeof(General).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annual Plan Name.
        /// </summary>
        public static string AnnualPlan_Name {
            get {
                return ResourceManager.GetString("AnnualPlan_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allocated Budget Amount.
        /// </summary>
        public static string BudgetItem_Amount {
            get {
                return ResourceManager.GetString("BudgetItem_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used Budget Amount.
        /// </summary>
        public static string BudgetItem_AmountUsed {
            get {
                return ResourceManager.GetString("BudgetItem_AmountUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string BudgetItem_Comments {
            get {
                return ResourceManager.GetString("BudgetItem_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Card.
        /// </summary>
        public static string BudgetItem_CreditCardType {
            get {
                return ResourceManager.GetString("BudgetItem_CreditCardType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string BudgetItem_Description {
            get {
                return ResourceManager.GetString("BudgetItem_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over Budget.
        /// </summary>
        public static string BudgetItem_OverBudget {
            get {
                return ResourceManager.GetString("BudgetItem_OverBudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payee.
        /// </summary>
        public static string BudgetItem_Payee {
            get {
                return ResourceManager.GetString("BudgetItem_Payee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Date.
        /// </summary>
        public static string BudgetItem_PaymentDate {
            get {
                return ResourceManager.GetString("BudgetItem_PaymentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used Percentage (% Used/Allocated Budget).
        /// </summary>
        public static string BudgetItem_UsagePercentage {
            get {
                return ResourceManager.GetString("BudgetItem_UsagePercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Date.
        /// </summary>
        public static string CreationDate {
            get {
                return ResourceManager.GetString("CreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Change Type.
        /// </summary>
        public static string CRUDType {
            get {
                return ResourceManager.GetString("CRUDType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Value.
        /// </summary>
        public static string CurrentValueAsText {
            get {
                return ResourceManager.GetString("CurrentValueAsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Name.
        /// </summary>
        public static string EntityPropertyName {
            get {
                return ResourceManager.GetString("EntityPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Date.
        /// </summary>
        public static string EventDate {
            get {
                return ResourceManager.GetString("EventDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Modified.
        /// </summary>
        public static string LastModified {
            get {
                return ResourceManager.GetString("LastModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allocated Budget.
        /// </summary>
        public static string MonthlyPlan_AllocatedBudget {
            get {
                return ResourceManager.GetString("MonthlyPlan_AllocatedBudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        public static string MonthlyPlan_Balance {
            get {
                return ResourceManager.GetString("MonthlyPlan_Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget for Allocation.
        /// </summary>
        public static string MonthlyPlan_BudgetForAllocation {
            get {
                return ResourceManager.GetString("MonthlyPlan_BudgetForAllocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget Items.
        /// </summary>
        public static string MonthlyPlan_BudgetItems {
            get {
                return ResourceManager.GetString("MonthlyPlan_BudgetItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string MonthlyPlan_Comments {
            get {
                return ResourceManager.GetString("MonthlyPlan_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string MonthlyPlan_MonthName {
            get {
                return ResourceManager.GetString("MonthlyPlan_MonthName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening Balance.
        /// </summary>
        public static string MonthlyPlan_OpeningBalance {
            get {
                return ResourceManager.GetString("MonthlyPlan_OpeningBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage of allocated expenses from total income.
        /// </summary>
        public static string MonthlyPlan_PercentOf_AllocatedExpensesVSIncome {
            get {
                return ResourceManager.GetString("MonthlyPlan_PercentOf_AllocatedExpensesVSIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage of income against allocated expenses.
        /// </summary>
        public static string MonthlyPlan_PercentOf_IncomeVsAllocatedExpenses {
            get {
                return ResourceManager.GetString("MonthlyPlan_PercentOf_IncomeVsAllocatedExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage of total income against actual budget usage.
        /// </summary>
        public static string MonthlyPlan_PercentOf_IncomeVsUsed {
            get {
                return ResourceManager.GetString("MonthlyPlan_PercentOf_IncomeVsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage of used budget items from allocations.
        /// </summary>
        public static string MonthlyPlan_PercentOf_UsedAmountVSAllocatedAmount {
            get {
                return ResourceManager.GetString("MonthlyPlan_PercentOf_UsedAmountVSAllocatedAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage of Used Budget from Total Income.
        /// </summary>
        public static string MonthlyPlan_PercentOf_UsedVsIncome {
            get {
                return ResourceManager.GetString("MonthlyPlan_PercentOf_UsedVsIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of Month Balance (Predicted).
        /// </summary>
        public static string MonthlyPlan_PredictedEndOfMonthBalance {
            get {
                return ResourceManager.GetString("MonthlyPlan_PredictedEndOfMonthBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Income.
        /// </summary>
        public static string MonthlyPlan_TotalIncome {
            get {
                return ResourceManager.GetString("MonthlyPlan_TotalIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unallocated Avaiable Budget.
        /// </summary>
        public static string MonthlyPlan_UnallocatedBudget {
            get {
                return ResourceManager.GetString("MonthlyPlan_UnallocatedBudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum of All Used Budgets Amounts.
        /// </summary>
        public static string MonthlyPlan_UsedBudget {
            get {
                return ResourceManager.GetString("MonthlyPlan_UsedBudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allocated expenses against total income.
        /// </summary>
        public static string MonthlyPlan_ValueOf_AllocatedExpensesVSIncome {
            get {
                return ResourceManager.GetString("MonthlyPlan_ValueOf_AllocatedExpensesVSIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income VS Allocated Expenses.
        /// </summary>
        public static string MonthlyPlan_ValueOf_IncomeVsAllocatedExpenses {
            get {
                return ResourceManager.GetString("MonthlyPlan_ValueOf_IncomeVsAllocatedExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual value of income VS used budget.
        /// </summary>
        public static string MonthlyPlan_ValueOf_IncomeVsUsed {
            get {
                return ResourceManager.GetString("MonthlyPlan_ValueOf_IncomeVsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual used budget VS allocations.
        /// </summary>
        public static string MonthlyPlan_ValueOf_UsedAmountVSAllocatedAmount {
            get {
                return ResourceManager.GetString("MonthlyPlan_ValueOf_UsedAmountVSAllocatedAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual used bugdet VS total income.
        /// </summary>
        public static string MonthlyPlan_ValueOf_UsedVsIncome {
            get {
                return ResourceManager.GetString("MonthlyPlan_ValueOf_UsedVsIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string MonthlyPlanTemplate_Comments {
            get {
                return ResourceManager.GetString("MonthlyPlanTemplate_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template Name.
        /// </summary>
        public static string MonthlyPlanTemplate_TemplateName {
            get {
                return ResourceManager.GetString("MonthlyPlanTemplate_TemplateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Value.
        /// </summary>
        public static string OriginalValueAsText {
            get {
                return ResourceManager.GetString("OriginalValueAsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
    }
}
